### ISSUE TITLE
Missing zero22pi function

### ISSUE THREAD

**Issue by adku1173** [hagenw/amtoolbox#1]
Hey there,

I try to use the function localizationerror.m, but sadly get the error 'Undefined function or variable 'zero22pi'.' Can not finde it anywhere in the newest version of the masterbranch.
Is it missing or am I doing something wrong? Is there something else in the function than just converting zero to 2pi?
Thank you in advance.

**Comment by hagenw** [comment]
Sorry, this is only a mirror of http://sourceforge.net/projects/amtoolbox, which is only updated from time to time.

I updated the master branch, if you still experience an error, please report on sourceforge.
